import type { Metadata } from "next";
import AdminLayout from "./layout/adminLayout";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

//* admin main layout(server layout)
export default function AdminServerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AdminLayout>{children}</AdminLayout>;
}
